In [4]:
pip install pandas sqlalchemy psycopg2-binary openpyxl watchdog

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in E:\Anaconda\Lib\site-packages (3.0.3)
Requirement already satisfied: sqlalchemy in E:\Anaconda\Lib\site-packages (2.0.51)
Requirement already satisfied: psycopg2-binary in .\AppData\Roaming\Python\Python314\site-packages (2.9.13)
Requirement already satisfied: openpyxl in E:\Anaconda\Lib\site-packages (3.1.5)
Requirement already satisfied: watchdog in E:\Anaconda\Lib\site-packages (4.0.2)
Requirement already satisfied: numpy>=2.3.3 in E:\Anaconda\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in E:\Anaconda\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in E:\Anaconda\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: greenlet>=1 in E:\Anaconda\Lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in E:\Anaconda\Lib\site-packages (from sqlalchemy) (4.16.0)
Requirement already satisfied: et_xmlfile in E:\Anaconda\Lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in E:\Anaconda\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [11]:
from pathlib import Path

BASE_DIR = Path(r"E:\Supermarket_Automation")

print("Folder exists:", BASE_DIR.exists())
print("Folder location:", BASE_DIR)

Folder exists: True
Folder location: E:\Supermarket_Automation

In [12]:
print(list(BASE_DIR.rglob("*.csv")))

[WindowsPath('E:/Supermarket_Automation/data/inventory/inventory.csv'), WindowsPath('E:/Supermarket_Automation/data/products/products.csv'), WindowsPath('E:/Supermarket_Automation/data/sales/sales.csv')]

In [14]:

import pandas as pd
from pathlib import Path

# Project folder
BASE_DIR = Path(r"E:\Supermarket_Automation")

# Read the three CSV files from your actual folders
products = pd.read_csv(BASE_DIR / "data" / "products" / "products.csv")
sales = pd.read_csv(BASE_DIR / "data" / "sales" / "sales.csv")
inventory = pd.read_csv(BASE_DIR / "data" / "inventory" / "inventory.csv")

# Display the first five records
print("PRODUCTS DATA")
display(products.head())

print("SALES DATA")
display(sales.head())

print("INVENTORY DATA")
display(inventory.head())

PRODUCTS DATA

,product_id,product_name,category,selling_price,cost_price,supplier,reorder_level
0,P0001,Daily Choice Milk 200 g,Dairy,459.35,350.99,FreshMart Distributors,20
1,P0002,Daily Choice Bread 200 g,Bakery,368.40,317.45,DailyNeeds Wholesale,32
2,P0003,Daily Choice Tomato 200 g,Fruits & Vegetables,635.82,439.32,GreenBasket Foods,28
3,P0004,Daily Choice Chips 500 g,Snacks,89.47,68.11,Metro Supply Co.,30
4,P0005,Daily Choice Water 500 g,Beverages,264.84,174.41,Sunrise Consumer Goods,29

SALES DATA

  bill_number   sale_date product_id  quantity  discount payment_method
0   BILL00001  2026-10-16      P0162         5      15.0           Cash
1   BILL00002  2026-10-19      P0185         5      10.0    Credit Card
2   BILL00003  2026-10-17      P0054         2       0.0    Credit Card
3   BILL00004  2026-10-05      P0168         4       0.0           Cash
4   BILL00005  2026-09-26      P0012         7      10.0         Wallet

INVENTORY DATA

,inventory_date,product_id,opening_stock,stock_received,damaged_units,stock_count,closing_stock
0,2026-10-23,P0001,115,6,1,112,112
1,2026-10-23,P0002,106,12,2,114,116
2,2026-10-23,P0003,105,63,2,162,163
3,2026-10-23,P0004,32,92,3,116,117
4,2026-10-23,P0005,62,72,3,131,131

In [15]:
print("Products:", products.shape)
print("Sales:", sales.shape)
print("Inventory:", inventory.shape)

Products: (200, 7)
Sales: (200, 6)
Inventory: (200, 7)

In [21]:
from sqlalchemy import create_engine, URL, text

# Enter your PostgreSQL credentials
db_url = URL.create(
    drivername="postgresql+psycopg2",
    username="postgres",
    password="pass",
    host="localhost",
    port=5432,
    database="supermarket_analytics "
)

engine = create_engine(db_url)

# Test the connection
with engine.connect() as connection:
    result = connection.execute(text("SELECT version()"))
    print("Connected successfully!")
    print(result.scalar())

Connected successfully!
PostgreSQL 18.6 on x86_64-windows, compiled by msvc-19.44.35229, 64-bit

In [22]:
# Load products first because other tables reference product_id
products.to_sql(
    "products",
    engine,
    if_exists="append",
    index=False
)

# Load sales transactions
sales.to_sql(
    "sales",
    engine,
    if_exists="append",
    index=False
)

# Load inventory records
inventory.to_sql(
    "inventory",
    engine,
    if_exists="append",
    index=False
)

print("All three datasets loaded successfully!")

All three datasets loaded successfully!

In [23]:
import pandas as pd
from pathlib import Path

# Project paths
BASE_DIR = Path(r"E:\Supermarket_Automation")
CLEAN_DIR = BASE_DIR / "cleaned"

CLEAN_DIR.mkdir(parents=True, exist_ok=True)

# Create copies so original data remains unchanged
products_clean = products.copy()
sales_clean = sales.copy()
inventory_clean = inventory.copy()

# Standardize column names
for df in [products_clean, sales_clean, inventory_clean]:
    df.columns = (
        df.columns.str.strip()
        .str.lower()
        .str.replace(" ", "_")
    )

# Standardize text fields
for df in [products_clean, sales_clean, inventory_clean]:
    for col in df.select_dtypes(include="object").columns:
        df[col] = df[col].str.strip()

# Convert dates
sales_clean["sale_date"] = pd.to_datetime(
    sales_clean["sale_date"], errors="coerce"
)

inventory_clean["inventory_date"] = pd.to_datetime(
    inventory_clean["inventory_date"], errors="coerce"
)

# Convert numeric columns
product_numeric = [
    "selling_price", "cost_price", "reorder_level"
]

sales_numeric = ["quantity", "discount"]

inventory_numeric = [
    "opening_stock",
    "stock_received",
    "damaged_units",
    "stock_count",
    "closing_stock"
]

for col in product_numeric:
    products_clean[col] = pd.to_numeric(
        products_clean[col], errors="coerce"
    )

for col in sales_numeric:
    sales_clean[col] = pd.to_numeric(
        sales_clean[col], errors="coerce"
    )

for col in inventory_numeric:
    inventory_clean[col] = pd.to_numeric(
        inventory_clean[col], errors="coerce"
    )

# Check required fields
required_fields = {
    "products": [
        "product_id", "product_name", "selling_price", "cost_price"
    ],
    "sales": [
        "bill_number", "sale_date", "product_id", "quantity"
    ],
    "inventory": [
        "inventory_date", "product_id", "closing_stock"
    ]
}

datasets = {
    "products": products_clean,
    "sales": sales_clean,
    "inventory": inventory_clean
}

for name, df in datasets.items():
    missing_columns = set(required_fields[name]) - set(df.columns)

    if missing_columns:
        raise ValueError(
            f"{name}: Missing required columns: {missing_columns}"
        )

# Report missing values
print("MISSING VALUES")
for name, df in datasets.items():
    print(f"\n{name.upper()}")
    print(df.isnull().sum())

# Report exact duplicate rows
print("\nEXACT DUPLICATE ROWS")
for name, df in datasets.items():
    print(f"{name}: {df.duplicated().sum()}")

# Check product IDs
product_ids = set(products_clean["product_id"].dropna())

unknown_sales_products = (
    set(sales_clean["product_id"].dropna()) - product_ids
)

unknown_inventory_products = (
    set(inventory_clean["product_id"].dropna()) - product_ids
)

print("\nPRODUCT ID VALIDATION")
print("Unknown product IDs in sales:", unknown_sales_products)
print("Unknown product IDs in inventory:", unknown_inventory_products)

# Check invalid values
print("\nBUSINESS VALIDATION")
print(
    "Invalid product prices:",
    ((products_clean["selling_price"] < 0) |
     (products_clean["cost_price"] < 0)).sum()
)

print(
    "Invalid sales quantities:",
    (sales_clean["quantity"] <= 0).sum()
)

print(
    "Negative inventory values:",
    (inventory_clean[inventory_numeric] < 0).sum().sum()
)

# Save cleaned-format files
# Invalid records are reported above, not silently deleted.
products_clean.to_csv(
    CLEAN_DIR / "products_clean.csv", index=False
)

sales_clean.to_csv(
    CLEAN_DIR / "sales_clean.csv", index=False
)

inventory_clean.to_csv(
    CLEAN_DIR / "inventory_clean.csv", index=False
)

print("\nFiles saved to:", CLEAN_DIR)
print("Data-quality checks completed.")

C:\Users\saira\AppData\Local\Temp\ipykernel_26160\3118995659.py:25: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:
C:\Users\saira\AppData\Local\Temp\ipykernel_26160\3118995659.py:25: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:
C:\Users\saira\AppData\Local\Temp\ipykernel_26160\3118995659.py:25: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:

MISSING VALUES

PRODUCTS
product_id       0
product_name     0
category         0
selling_price    0
cost_price       0
supplier         0
reorder_level    0
dtype: int64

SALES
bill_number       0
sale_date         0
product_id        0
quantity          0
discount          0
payment_method    0
dtype: int64

INVENTORY
inventory_date    0
product_id        0
opening_stock     0
stock_received    0
damaged_units     0
stock_count       0
closing_stock     0
dtype: int64

EXACT DUPLICATE ROWS
products: 0
sales: 0
inventory: 0

PRODUCT ID VALIDATION
Unknown product IDs in sales: set()
Unknown product IDs in inventory: set()

BUSINESS VALIDATION
Invalid product prices: 0
Invalid sales quantities: 0
Negative inventory values: 0

Files saved to: E:\Supermarket_Automation\cleaned
Data-quality checks completed.

In [24]:
from pathlib import Path

CLEAN_DIR = Path(r"E:\Supermarket_Automation\cleaned")

for file in CLEAN_DIR.glob("*.csv"):
    print(file.name, "Exists:", file.exists())

inventory_clean.csv Exists: True
products_clean.csv Exists: True
sales_clean.csv Exists: True

In [5]:
import pandas as pd
from pathlib import Path

BASE_DIR = Path(r"E:\Supermarket_Automation")
CLEAN_DIR = BASE_DIR / "cleaned"

# Load the cleaned datasets
products_clean = pd.read_csv(CLEAN_DIR / "products_clean.csv")
sales_clean = pd.read_csv(CLEAN_DIR / "sales_clean.csv")
inventory_clean = pd.read_csv(CLEAN_DIR / "inventory_clean.csv")

print("PRODUCT COLUMNS:")
print(products_clean.columns.tolist())

print("\nSALES COLUMNS:")
print(sales_clean.columns.tolist())

print("\nINVENTORY COLUMNS:")
print(inventory_clean.columns.tolist())

PRODUCT COLUMNS:
['product_id', 'product_name', 'category', 'selling_price', 'cost_price', 'supplier', 'reorder_level']

SALES COLUMNS:
['bill_number', 'sale_date', 'product_id', 'quantity', 'discount', 'payment_method']

INVENTORY COLUMNS:
['inventory_date', 'product_id', 'opening_stock', 'stock_received', 'damaged_units', 'stock_count', 'closing_stock']

In [7]:
from sqlalchemy import text

with engine.connect() as connection:
    for table in ["products", "sales", "inventory"]:
        query = text("""
            SELECT column_name, data_type
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = :table_name
            ORDER BY ordinal_position
        """)

        result = connection.execute(
            query, {"table_name": table}
        )

        print(f"\n--- {table.upper()} TABLE ---")

        for row in result:
            print(row)

NameError: name 'engine' is not defined

In [8]:
from sqlalchemy import create_engine, URL, text

# PostgreSQL connection settings
db_url = URL.create(
    drivername="postgresql+psycopg2",
    username="postgres",
    password="pass",
    host="localhost",
    port=5432,
    database="supermarket_analytics "
)

engine = create_engine(db_url)

# Test the connection
with engine.connect() as connection:
    result = connection.execute(text("SELECT version()"))
    print("PostgreSQL connected successfully!")
    print(result.scalar())

PostgreSQL connected successfully!
PostgreSQL 18.6 on x86_64-windows, compiled by msvc-19.44.35229, 64-bit

In [9]:
from sqlalchemy import text

with engine.connect() as connection:
    for table in ["products", "sales", "inventory"]:

        query = text("""
            SELECT column_name, data_type
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = :table_name
            ORDER BY ordinal_position
        """)

        result = connection.execute(
            query,
            {"table_name": table}
        )

        print(f"\n--- {table.upper()} TABLE ---")

        for row in result:
            print(row)

--- PRODUCTS TABLE ---
('product_id', 'character varying')
('product_name', 'character varying')
('category', 'character varying')
('selling_price', 'numeric')
('cost_price', 'numeric')
('supplier', 'character varying')
('reorder_level', 'integer')

--- SALES TABLE ---
('sales_id', 'bigint')
('bill_number', 'character varying')
('sale_date', 'date')
('product_id', 'character varying')
('quantity', 'integer')
('discount', 'numeric')
('payment_method', 'character varying')

--- INVENTORY TABLE ---
('inventory_id', 'bigint')
('inventory_date', 'date')
('product_id', 'character varying')
('opening_stock', 'integer')
('stock_received', 'integer')
('damaged_units', 'integer')
('stock_count', 'integer')
('closing_stock', 'integer')

In [11]:
from sqlalchemy import text

with engine.connect() as connection:
    for table in ["products", "sales", "inventory"]:

        query = text("""
            SELECT column_name, data_type
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = :table_name
            ORDER BY ordinal_position
        """)

        result = connection.execute(
            query,
            {"table_name": table}
        )

        print(f"\n--- {table.upper()} TABLE ---")

        columns = result.fetchall()

        if columns:
            for column in columns:
                print(column)
        else:
            print("Table not found in the public schema.")

--- PRODUCTS TABLE ---
('product_id', 'character varying')
('product_name', 'character varying')
('category', 'character varying')
('selling_price', 'numeric')
('cost_price', 'numeric')
('supplier', 'character varying')
('reorder_level', 'integer')

--- SALES TABLE ---
('sales_id', 'bigint')
('bill_number', 'character varying')
('sale_date', 'date')
('product_id', 'character varying')
('quantity', 'integer')
('discount', 'numeric')
('payment_method', 'character varying')

--- INVENTORY TABLE ---
('inventory_id', 'bigint')
('inventory_date', 'date')
('product_id', 'character varying')
('opening_stock', 'integer')
('stock_received', 'integer')
('damaged_units', 'integer')
('stock_count', 'integer')
('closing_stock', 'integer')

In [12]:
from sqlalchemy import text

with engine.connect() as connection:
    query = text("""
        SELECT table_name
        FROM information_schema.tables
        WHERE table_schema = 'public'
        ORDER BY table_name;
    """)

    tables = connection.execute(query).fetchall()

    print("Tables in your PostgreSQL database:")

    for table in tables:
        print(table[0])

Tables in your PostgreSQL database:
inventory
products
sales

In [13]:
from sqlalchemy import text

with engine.connect() as connection:
    for table in ["products", "sales", "inventory"]:
        print(f"\n--- {table.upper()} ---")

        result = connection.execute(text("""
            SELECT
                column_name,
                data_type,
                is_nullable,
                column_default
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = :table_name
            ORDER BY ordinal_position
        """), {"table_name": table})

        for row in result:
            print(row)

--- PRODUCTS ---
('product_id', 'character varying', 'NO', None)
('product_name', 'character varying', 'YES', None)
('category', 'character varying', 'YES', None)
('selling_price', 'numeric', 'YES', None)
('cost_price', 'numeric', 'YES', None)
('supplier', 'character varying', 'YES', None)
('reorder_level', 'integer', 'YES', None)

--- SALES ---
('sales_id', 'bigint', 'NO', None)
('bill_number', 'character varying', 'YES', None)
('sale_date', 'date', 'YES', None)
('product_id', 'character varying', 'YES', None)
('quantity', 'integer', 'YES', None)
('discount', 'numeric', 'YES', None)
('payment_method', 'character varying', 'YES', None)

--- INVENTORY ---
('inventory_id', 'bigint', 'NO', None)
('inventory_date', 'date', 'YES', None)
('product_id', 'character varying', 'YES', None)
('opening_stock', 'integer', 'YES', None)
('stock_received', 'integer', 'YES', None)
('damaged_units', 'integer', 'YES', None)
('stock_count', 'integer', 'YES', None)
('closing_stock', 'integer', 'YES', None)

In [15]:

from sqlalchemy import text

with engine.connect() as connection:
    for table in ["products", "sales", "inventory"]:
        count = connection.execute(
            text(f'SELECT COUNT(*) FROM public."{table}"')
        ).scalar_one()

        print(f"{table}: {count} records")

products: 200 records
sales: 200 records
inventory: 200 records

In [16]:
from pathlib import Path

BASE_DIR = Path(r"E:\Supermarket_Automation")

folders = [
    "incoming/products",
    "incoming/sales",
    "incoming/inventory",
    "processed/products",
    "processed/sales",
    "processed/inventory",
    "rejected",
    "logs"
]

for folder in folders:
    (BASE_DIR / folder).mkdir(parents=True, exist_ok=True)

print("All project folders are ready!")

for folder in folders:
    print(BASE_DIR / folder)

All project folders are ready!
E:\Supermarket_Automation\incoming\products
E:\Supermarket_Automation\incoming\sales
E:\Supermarket_Automation\incoming\inventory
E:\Supermarket_Automation\processed\products
E:\Supermarket_Automation\processed\sales
E:\Supermarket_Automation\processed\inventory
E:\Supermarket_Automation\rejected
E:\Supermarket_Automation\logs

In [23]:
import pandas as pd
import shutil
import logging
from pathlib import Path
from sqlalchemy import text

BASE_DIR = Path(r"E:\Supermarket_Automation")

INCOMING_SALES = BASE_DIR / "incoming" / "sales"
PROCESSED_SALES = BASE_DIR / "processed" / "sales"
LOG_DIR = BASE_DIR / "logs"

LOG_DIR.mkdir(parents=True, exist_ok=True)

logging.basicConfig(
    filename=str(LOG_DIR / "sales_import.log"),
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)

REQUIRED_COLUMNS = [
    "bill_number",
    "sale_date",
    "product_id",
    "quantity",
    "discount",
    "payment_method"
]


def import_sales_file(file_path):

    file_path = Path(file_path)

    if not file_path.exists():
        raise FileNotFoundError(f"File not found: {file_path}")

    try:
        df = pd.read_csv(file_path)

        # Standardize column names
        df.columns = df.columns.str.strip().str.lower()

        # Check required columns
        missing_columns = set(REQUIRED_COLUMNS) - set(df.columns)

        if missing_columns:
            raise ValueError(
                f"Missing required columns: {sorted(missing_columns)}"
            )

        df = df[REQUIRED_COLUMNS].copy()

        # Clean text fields
        for col in ["bill_number", "product_id", "payment_method"]:
            df[col] = df[col].astype("string").str.strip()

        # Validate dates and numeric values
        df["sale_date"] = pd.to_datetime(
            df["sale_date"], errors="coerce"
        ).dt.date

        df["quantity"] = pd.to_numeric(
            df["quantity"], errors="coerce"
        )

        df["discount"] = pd.to_numeric(
            df["discount"], errors="coerce"
        )

        if df.isna().any().any():
            raise ValueError(
                "The file contains missing or invalid required values."
            )

        if (df["quantity"] <= 0).any():
            raise ValueError("Quantity must be greater than zero.")

        if (df["discount"] < 0).any():
            raise ValueError("Discount cannot be negative.")

        # Remove exact duplicate rows within this file
        before = len(df)
        df = df.drop_duplicates()
        duplicates_removed = before - len(df)

        # Ensure numeric quantities are integers
        if not (df["quantity"] % 1 == 0).all():
            raise ValueError("Quantity must contain whole numbers.")

        df["quantity"] = df["quantity"].astype("int64")

        # Check product IDs against PostgreSQL
        with engine.begin() as connection:

            product_ids = set(
                connection.execute(
                    text("SELECT product_id FROM public.products")
                ).scalars().all()
            )

            unknown_ids = set(df["product_id"]) - product_ids

            if unknown_ids:
                raise ValueError(
                    f"Unknown product IDs: {sorted(unknown_ids)[:10]}"
                )

            # Insert sales; PostgreSQL generates sales_id.
            # This is a test-stage importer, so we do not yet
            # treat bill_number alone as a unique transaction key.
            df.to_sql(
                "sales",
                con=connection,
                schema="public",
                if_exists="append",
                index=False,
                method="multi"
            )

        # Archive only after the database transaction succeeds
        destination = PROCESSED_SALES / file_path.name

        if destination.exists():
            raise FileExistsError(
                f"Archive file already exists: {destination}"
            )

        shutil.move(str(file_path), str(destination))

        logging.info(
            "Imported %s: %s rows; removed %s exact duplicate rows.",
            file_path.name,
            len(df),
            duplicates_removed
        )

        print("Import successful!")
        print("Rows inserted:", len(df))
        print("Duplicate rows removed:", duplicates_removed)
        print("Archived file:", destination)

    except Exception as exc:
        logging.exception("Sales import failed for %s", file_path.name)
        print("Import failed:", exc)
        print("Original file has not intentionally been moved.")

In [24]:
print("Sales import function defined:", callable(import_sales_file))
print("Incoming folder exists:", INCOMING_SALES.exists())
print("Processed folder exists:", PROCESSED_SALES.exists())

Sales import function defined: True
Incoming folder exists: True
Processed folder exists: True

In [25]:
from sqlalchemy import text

with engine.begin() as connection:
    connection.execute(text("""
        CREATE TABLE IF NOT EXISTS public.file_import_log (
            import_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            file_name TEXT NOT NULL,
            file_hash TEXT NOT NULL UNIQUE,
            import_status TEXT NOT NULL,
            rows_imported INTEGER DEFAULT 0,
            imported_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
    """))

print("Import tracking table is ready!")

Import tracking table is ready!

In [26]:
with engine.connect() as connection:
    result = connection.execute(text("""
        SELECT table_name
        FROM information_schema.tables
        WHERE table_schema = 'public'
          AND table_name = 'file_import_log';
    """))

    print(result.fetchall())

[('file_import_log',)]

In [27]:
import hashlib
import pandas as pd
import shutil

from pathlib import Path
from sqlalchemy import text

In [28]:

def import_sales_file(file_path):

    file_path = Path(file_path)

    if not file_path.exists():
        print("File not found:", file_path)
        return

    try:
        # Calculate a hash of the original file
        file_hash = hashlib.sha256(
            file_path.read_bytes()
        ).hexdigest()

        # Read the CSV
        df = pd.read_csv(file_path)
        df.columns = df.columns.str.strip().str.lower()

        required_columns = [
            "bill_number",
            "sale_date",
            "product_id",
            "quantity",
            "discount",
            "payment_method"
        ]

        missing = set(required_columns) - set(df.columns)

        if missing:
            raise ValueError(
                f"Missing columns: {sorted(missing)}"
            )

        df = df[required_columns].copy()

        # Standardize text fields
        for col in [
            "bill_number",
            "product_id",
            "payment_method"
        ]:
            df[col] = df[col].astype("string").str.strip()

        # Validate dates and numeric values
        df["sale_date"] = pd.to_datetime(
            df["sale_date"], errors="coerce"
        ).dt.date

        df["quantity"] = pd.to_numeric(
            df["quantity"], errors="coerce"
        )

        df["discount"] = pd.to_numeric(
            df["discount"], errors="coerce"
        )

        if df.isna().any().any():
            raise ValueError(
                "Missing or invalid required values found."
            )

        if (df["quantity"] <= 0).any():
            raise ValueError(
                "Quantity must be greater than zero."
            )

        if (df["discount"] < 0).any():
            raise ValueError(
                "Discount cannot be negative."
            )

        if not (df["quantity"] % 1 == 0).all():
            raise ValueError(
                "Quantity must contain whole numbers."
            )

        df["quantity"] = df["quantity"].astype("int64")

        # Remove exact duplicate rows within this file
        df = df.drop_duplicates()

        # Check the archive destination before importing
        destination = PROCESSED_SALES / file_path.name

        if destination.exists():
            raise FileExistsError(
                f"Archive file already exists: {destination}"
            )

        # Insert sales and tracking record atomically
        with engine.begin() as connection:

            previous_import = connection.execute(
                text("""
                    SELECT import_id
                    FROM public.file_import_log
                    WHERE file_hash = :file_hash
                """),
                {"file_hash": file_hash}
            ).first()

            if previous_import:
                print(
                    "Duplicate file detected. "
                    "No records imported."
                )
                return

            # Validate product IDs
            product_ids = set(
                connection.execute(
                    text("""
                        SELECT product_id
                        FROM public.products
                    """)
                ).scalars().all()
            )

            unknown_ids = (
                set(df["product_id"]) - product_ids
            )

            if unknown_ids:
                raise ValueError(
                    f"Unknown product IDs: "
                    f"{sorted(unknown_ids)[:10]}"
                )

            # Insert sales; PostgreSQL generates sales_id
            df.to_sql(
                "sales",
                con=connection,
                schema="public",
                if_exists="append",
                index=False,
                method="multi"
            )

            # Record the successful import
            connection.execute(
                text("""
                    INSERT INTO public.file_import_log
                        (file_name, file_hash,
                         import_status, rows_imported)
                    VALUES
                        (:file_name, :file_hash,
                         'SUCCESS', :rows_imported)
                """),
                {
                    "file_name": file_path.name,
                    "file_hash": file_hash,
                    "rows_imported": len(df)
                }
            )

        # Move the file only after the database commits
        shutil.move(
            str(file_path),
            str(destination)
        )

        print("Import successful!")
        print("Rows imported:", len(df))
        print("Archived at:", destination)

    except Exception as exc:
        print("Import failed:", exc)

In [29]:
print("Importer ready:", callable(import_sales_file))
print("Incoming sales folder:", INCOMING_SALES)
print("Processed sales folder:", PROCESSED_SALES)

Importer ready: True
Incoming sales folder: E:\Supermarket_Automation\incoming\sales
Processed sales folder: E:\Supermarket_Automation\processed\sales

In [30]:
from sqlalchemy import text

with engine.begin() as connection:
    connection.execute(text("""
        CREATE OR REPLACE VIEW vw_sales_analysis AS
        SELECT
            s.bill_number,
            s.sale_date,
            s.product_id,
            p.product_name,
            p.category,
            s.quantity,
            p.selling_price,
            p.cost_price,
            s.discount,
            s.payment_method,

            (s.quantity * p.selling_price) AS gross_sales,

            (s.quantity * p.selling_price * s.discount / 100.0)
                AS discount_amount,

            (s.quantity * p.selling_price)
                - (s.quantity * p.selling_price * s.discount / 100.0)
                AS net_sales,

            (s.quantity * p.cost_price) AS total_cost,

            ((s.quantity * p.selling_price)
                - (s.quantity * p.selling_price * s.discount / 100.0)
                - (s.quantity * p.cost_price))
                AS profit

        FROM sales s
        JOIN products p
            ON s.product_id = p.product_id;
    """))

print("Sales analysis view created successfully!")

Sales analysis view created successfully!

In [31]:
import pandas as pd
from sqlalchemy import text

with engine.connect() as connection:
    sales_analysis = pd.read_sql(
        text("SELECT * FROM vw_sales_analysis LIMIT 10"),
        connection
    )

display(sales_analysis)

,bill_number,sale_date,product_id,product_name,category,quantity,selling_price,cost_price,discount,payment_method,gross_sales,discount_amount,net_sales,total_cost,profit
0,BILL00001,2026-10-16,P0162,FreshWay Rusk Family pack,Bakery,5,93.60,60.44,15.0,Cash,468.00,70.2000,397.8000,302.20,95.6000
1,BILL00002,2026-10-19,P0185,HomeSelect Water 500 g,Beverages,5,310.64,262.72,10.0,Credit Card,1553.20,155.3200,1397.8800,1313.60,84.2800
2,BILL00003,2026-10-17,P0054,Daily Choice Popcorn Family pack,Snacks,2,225.26,163.93,0.0,Credit Card,450.52,0.0000,450.5200,327.86,122.6600
3,BILL00004,2026-10-05,P0168,FreshWay Cooking Oil 500 g,Staples,4,149.36,98.81,0.0,Cash,597.44,0.0000,597.4400,395.24,202.2000
4,BILL00005,2026-09-26,P0012,FreshWay Bun 1 L,Bakery,7,112.50,79.58,10.0,Wallet,787.50,78.7500,708.7500,557.06,151.6900
5,BILL00006,2026-09-26,P0012,FreshWay Bun 1 L,Bakery,3,112.50,79.58,2.0,UPI,337.50,6.7500,330.7500,238.74,92.0100
6,BILL00007,2026-09-29,P0098,Nature Basket Salt 1 kg,Staples,6,337.53,244.48,0.0,Cash,2025.18,0.0000,2025.1800,1466.88,558.3000
7,BILL00008,2026-10-21,P0149,Nature Basket Frozen Snacks 500 g,Frozen Foods,1,427.76,345.99,2.0,Wallet,427.76,8.5552,419.2048,345.99,73.2148
8,BILL00009,2026-10-19,P0142,Nature Basket Cake Family pack,Bakery,4,346.89,262.72,0.0,Debit Card,1387.56,0.0000,1387.5600,1050.88,336.6800
9,BILL00010,2026-10-01,P0031,HomeSelect Cheese 2 pack,Dairy,5,168.55,135.25,5.0,Cash,842.75,42.1375,800.6125,676.25,124.3625

In [32]:
with engine.connect() as connection:
    result = connection.execute(text("""
        SELECT
            COUNT(*) AS total_transactions,
            ROUND(SUM(net_sales)::numeric, 2) AS total_sales,
            ROUND(SUM(profit)::numeric, 2) AS total_profit
        FROM vw_sales_analysis;
    """))

    print(result.fetchone())

(200, Decimal('263833.92'), Decimal('57750.41'))

In [33]:
from sqlalchemy import text

with engine.begin() as connection:
    connection.execute(text("""
        CREATE OR REPLACE VIEW vw_inventory_analysis AS
        SELECT
            i.inventory_date,
            i.product_id,
            p.product_name,
            p.category,
            i.opening_stock,
            i.stock_received,
            i.damaged_units,
            i.stock_count,
            i.closing_stock,
            p.reorder_level,

            CASE
                WHEN i.closing_stock <= 0
                    THEN 'Out of Stock'
                WHEN i.closing_stock <= p.reorder_level
                    THEN 'Low Stock'
                ELSE 'Available'
            END AS stock_status,

            CASE
                WHEN i.closing_stock <= p.reorder_level
                    THEN GREATEST(
                        p.reorder_level * 2 - i.closing_stock,
                        0
                    )
                ELSE 0
            END AS suggested_reorder_quantity

        FROM inventory i
        JOIN products p
            ON i.product_id = p.product_id;
    """))

print("Inventory analysis view created successfully!")

Inventory analysis view created successfully!

In [34]:
import pandas as pd
from sqlalchemy import text

with engine.connect() as connection:
    inventory_analysis = pd.read_sql(
        text("""
            SELECT *
            FROM vw_inventory_analysis
            ORDER BY closing_stock ASC
            LIMIT 15
        """),
        connection
    )

display(inventory_analysis)

,inventory_date,product_id,product_name,category,opening_stock,stock_received,damaged_units,stock_count,closing_stock,reorder_level,stock_status,suggested_reorder_quantity
0,2026-10-23,P0081,HomeSelect Butter 1 kg,Dairy,26,3,1,17,16,21,Low Stock,26
1,2026-10-23,P0127,Value Plus Detergent 200 g,Household,20,11,2,20,19,13,Available,0
2,2026-10-23,P0171,Value Plus Yogurt 1 kg,Dairy,28,10,1,24,22,16,Available,0
3,2026-10-23,P0067,FreshWay Detergent 2 pack,Household,27,9,3,28,27,20,Available,0
4,2026-10-23,P0118,FreshWay Lentils 1 L,Staples,18,21,4,26,28,33,Low Stock,38
5,2026-10-23,P0023,Value Plus Onion 500 g,Fruits & Vegetables,50,1,4,28,29,22,Available,0
6,2026-10-23,P0033,HomeSelect Apple 2 pack,Fruits & Vegetables,22,32,3,32,30,19,Available,0
7,2026-10-23,P0083,HomeSelect Onion 1 L,Fruits & Vegetables,18,14,0,34,32,8,Available,0
8,2026-10-23,P0177,Value Plus Air Freshener 2 pack,Household,22,28,3,34,35,30,Available,0
9,2026-10-23,P0165,FreshWay Coffee 200 g,Beverages,21,27,3,35,37,25,Available,0
10,2026-10-23,P0070,FreshWay Baby Wipes Family pack,Baby Care,39,5,1,43,42,15,Available,0
11,2026-10-23,P0053,Daily Choice Spinach Family pack,Fruits & Vegetables,41,13,3,44,43,35,Available,0
12,2026-10-23,P0186,HomeSelect Soap 500 g,Personal Care,36,9,2,45,43,34,Available,0
13,2026-10-23,P0093,Nature Basket Apple 200 g,Fruits & Vegetables,33,17,0,52,50,8,Available,0
14,2026-10-23,P0132,HomeSelect Bun 500 g,Bakery,22,32,2,53,51,22,Available,0

In [35]:
with engine.connect() as connection:
    result = connection.execute(text("""
        SELECT
            stock_status,
            COUNT(*) AS product_records
        FROM vw_inventory_analysis
        GROUP BY stock_status
        ORDER BY product_records DESC;
    """))

    for row in result:
        print(row)

('Available', 198)
('Low Stock', 2)

In [37]:

import pandas as pd


REQUIRED_COLUMNS = {
    "products": [
        "product_id",
        "product_name",
        "category",
        "cost_price",
        "selling_price",
        "reorder_level"
    ],
    "sales": [
        "bill_number",
        "sale_date",
        "product_id",
        "quantity",
        "discount",
        "payment_method"
    ],
    "inventory": [
        "inventory_date",
        "product_id",
        "opening_stock",
        "stock_received",
        "damaged_units",
        "stock_count",
        "closing_stock"
    ]
}


def validate_file(file_path, file_type):
    """
    Validate the structure and basic data quality of an incoming CSV.
    Returns (True, message) if valid, otherwise (False, message).
    """

    if file_type not in REQUIRED_COLUMNS:
        return False, f"Unsupported file type: {file_type}"

    try:
        df = pd.read_csv(file_path)
    except Exception as error:
        return False, f"Could not read CSV: {error}"

    # Check required columns
    missing_columns = set(REQUIRED_COLUMNS[file_type]) - set(df.columns)

    if missing_columns:
        return False, f"Missing required columns: {sorted(missing_columns)}"

    if df.empty:
        return False, "The CSV file contains no data."

    # Check for missing values in required columns
    if df[REQUIRED_COLUMNS[file_type]].isnull().any().any():
        return False, "Required columns contain missing values."

    # Check numeric fields
    numeric_columns = {
        "products": [
            "product_id", "cost_price",
            "selling_price", "reorder_level"
        ],
        "sales": ["product_id", "quantity", "discount"],
        "inventory": [
            "product_id", "opening_stock", "stock_received",
            "damaged_units", "stock_count", "closing_stock"
        ]
    }

    for column in numeric_columns[file_type]:
        converted = pd.to_numeric(df[column], errors="coerce")

        if converted.isnull().any():
            return False, f"Column '{column}' contains non-numeric values."

        if (converted < 0).any():
            return False, f"Column '{column}' contains negative values."

    return True, f"Validation successful: {len(df)} rows checked."

In [38]:
import sys

sys.path.insert(
    0,
    r"E:\Supermarket_Automation\python"
)

from validate_data import validate_file

print("Validation module imported successfully."

_IncompleteInputError: incomplete input (1122509749.py, line 10)

In [41]:

import sys

sys.path.insert(
    0,
    r"E:\Supermarket_Automation\python"
)

from validate_data import validate_file

print("Validation module imported successfully.")

ModuleNotFoundError: No module named 'validate_data'

In [43]:

from pathlib import Path

file_path = Path(r"E:\Supermarket_Automation\python\validate_data.py")

print("File exists:", file_path.exists())
print("Python folder exists:", file_path.parent.exists())

File exists: False
Python folder exists: True

In [45]:
from pathlib import Path

print(
    Path(
        r"E:\Supermarket_Automation\python\validate_data.py"
    ).exists()
)

False

In [46]:
from pathlib import Path

base = Path(r"E:\Supermarket_Automation")

print("Project folder exists:", base.exists())

for file in base.rglob("validate_data*"):
    print("Found file:", file)

Project folder exists: True
Found file: E:\Supermarket_Automation\python\validate_data.py.txt

In [47]:
from pathlib import Path

old_file = Path(
    r"E:\Supermarket_Automation\python\validate_data.py.txt"
)

new_file = Path(
    r"E:\Supermarket_Automation\python\validate_data.py"
)

old_file.rename(new_file)

print("File renamed successfully:", new_file.exists())

File renamed successfully: True

In [52]:

import sys
import importlib

sys.path.insert(0, r"E:\Supermarket_Automation\python")

import validate_data
importlib.reload(validate_data)

print("Validation module imported successfully!")

Validation module imported successfully!

In [53]:
import sys
import importlib

sys.path.insert(0, r"E:\Supermarket_Automation\python")

import validate_data
importlib.reload(validate_data)

print("Validation module ready!")

Validation module ready!

In [54]:
result = validate_data.validate_file(
    r"E:\Supermarket_Automation\data\products\products.csv",
    "products"
)

print("Validation result:", result)

Validation result: (True, 'Validation successful: 200 rows checked.')

In [55]:
result = validate_data.validate_file(
    r"E:\Supermarket_Automation\data\sales\sales.csv",
    "sales"
)

print("Validation result:", result)

Validation result: (True, 'Validation successful: 200 rows checked.')

In [56]:
result = validate_data.validate_file(
    r"E:\Supermarket_Automation\data\inventory\inventory.csv",
    "inventory"
)

print("Validation result:", result)

Validation result: (True, 'Validation successful: 200 rows checked.')

In [57]:
import sys
import importlib

sys.path.insert(0, r"E:\Supermarket_Automation\python")

import clean_data
importlib.reload(clean_data)

print("Cleaning module imported successfully!")

ModuleNotFoundError: No module named 'clean_data'

In [59]:

from pathlib import Path

folder = Path(r"E:\Supermarket_Automation\python")

print("Python folder exists:", folder.exists())

for file in folder.glob("clean_data*"):
    print("Found:", file.name)

Python folder exists: True
Found: clean_data.py.txt

In [60]:
from pathlib import Path

folder = Path(r"E:\Supermarket_Automation\python")

old_file = folder / "clean_data.py.txt"
new_file = folder / "clean_data.py"

old_file.rename(new_file)

print("File renamed successfully:", new_file.exists())

File renamed successfully: True

In [61]:
import sys
import importlib

sys.path.insert(0, r"E:\Supermarket_Automation\python")

import clean_data
importlib.reload(clean_data)

print("Cleaning module imported successfully!")

Cleaning module imported successfully!

In [62]:
import pandas as pd

products_test = pd.read_csv(
    r"E:\Supermarket_Automation\data\products\products.csv"
)

products_cleaned_test = clean_data.clean_data(
    products_test,
    "products"
)

print(products_cleaned_test.head())

Rows before cleaning: 200
Duplicate rows removed: 0
Rows after cleaning: 200
   product_id               product_name             category  selling_price  \
0         NaN    Daily Choice Milk 200 g                Dairy         459.35
1         NaN   Daily Choice Bread 200 g               Bakery         368.40
2         NaN  Daily Choice Tomato 200 g  Fruits & Vegetables         635.82
3         NaN   Daily Choice Chips 500 g               Snacks          89.47
4         NaN   Daily Choice Water 500 g            Beverages         264.84

   cost_price                supplier  reorder_level
0      350.99  FreshMart Distributors             20
1      317.45    DailyNeeds Wholesale             32
2      439.32       GreenBasket Foods             28
3       68.11        Metro Supply Co.             30
4      174.41  Sunrise Consumer Goods             29

In [63]:
print(engine)

Engine(postgresql+psycopg2://postgres:***@localhost:5432/supermarket_analytics )

In [64]:
print("Sales import function exists:", callable(import_sales_file))

Sales import function exists: True

In [65]:
import sys
import importlib

sys.path.insert(0, r"E:\Supermarket_Automation\python")

import main
importlib.reload(main)

print("Main pipeline imported successfully!")

Main pipeline imported successfully!

In [66]:
main.main()

In [67]:
print("Main module loaded:", main)
print("Main function exists:", callable(main.main))

Main module loaded: <module 'main' from 'E:\\Supermarket_Automation\\python\\main.py'>
Main function exists: True

In [68]:
print("Starting supermarket automation...")

main.main()

print("Automation test finished.")

Starting supermarket automation...
Automation test finished.

In [70]:
from pathlib import Path

base = Path(r"E:\Supermarket_Automation")

for folder in ["products", "sales", "inventory"]:
    path = base / "incoming" / folder
    files = list(path.glob("*.csv")) if path.exists() else []

    print(f"{folder}: {len(files)} CSV file(s) found")

products: 0 CSV file(s) found
sales: 0 CSV file(s) found
inventory: 0 CSV file(s) found

In [71]:
from sqlalchemy import text

with engine.connect() as connection:
    result = connection.execute(
        text("SELECT current_database();")
    )
    print("Connected database:", result.scalar())

Connected database: supermarket_analytics

In [72]:
import importlib
import main

importlib.reload(main)
main.test_database_connection()

Database URL not configured.

False

In [73]:
print(engine.url.render_as_string(hide_password=True))

postgresql+psycopg2://postgres:***@localhost:5432/supermarket_analytics

In [74]:
import os

os.environ["SUPERMARKET_DATABASE_URL"] = engine.url.render_as_string(
    hide_password=False
)

print("Database URL configured:", bool(os.environ.get("SUPERMARKET_DATABASE_URL")))

Database URL configured: True

In [75]:
import importlib
import main

importlib.reload(main)
main.test_database_connection()

Connected to PostgreSQL: supermarket_analytics

True

In [76]:
print("Sales import function exists:", "import_sales_file" in globals())
print("Database engine exists:", "engine" in globals())

Sales import function exists: True
Database engine exists: True

In [77]:
import pandas as pd
from sqlalchemy import text

query = """
SELECT 'products' AS table_name, COUNT(*) AS total_rows FROM products
UNION ALL
SELECT 'sales', COUNT(*) FROM sales
UNION ALL
SELECT 'inventory', COUNT(*) FROM inventory
UNION ALL
SELECT 'file_import_log', COUNT(*) FROM file_import_log;
"""

with engine.connect() as connection:
table_counts = pd.read_sql(text(query), connection)

display(table_counts)

IndentationError: expected an indented block after 'with' statement on line 14 (2637458784.py, line 15)

In [78]:
import pandas as pd
from sqlalchemy import text

query = """
SELECT 'products' AS table_name, COUNT(*) AS total_rows FROM products
UNION ALL
SELECT 'sales', COUNT(*) FROM sales
UNION ALL
SELECT 'inventory', COUNT(*) FROM inventory
UNION ALL
SELECT 'file_import_log', COUNT(*) FROM file_import_log;
"""

with engine.connect() as connection:
table_counts = pd.read_sql(query, connection)

display(table_counts)

IndentationError: expected an indented block after 'with' statement on line 14 (1649096839.py, line 15)

In [79]:
import pandas as pd

query = """
SELECT 'products' AS table_name, COUNT(*) AS total_rows FROM products
UNION ALL
SELECT 'sales', COUNT(*) FROM sales
UNION ALL
SELECT 'inventory', COUNT(*) FROM inventory
UNION ALL
SELECT 'file_import_log', COUNT(*) FROM file_import_log
"""

table_counts = pd.read_sql_query(query, engine)
display(table_counts)

        table_name  total_rows
0         products         200
1            sales         200
2        inventory         200
3  file_import_log           0

In [82]:
from sqlalchemy import inspect

inspector = inspect(engine)

for table in ["products", "sales", "inventory"]:
print("\nTABLE:", table)
for column in inspector.get_columns(table):
print(column["name"], "-", column["type"])

IndentationError: expected an indented block after 'for' statement on line 5 (423091011.py, line 6)

In [83]:
from sqlalchemy import inspect

inspector = inspect(engine)

for table in ["products", "sales", "inventory"]:
print("\nTABLE:", table)
for column in inspector.get_columns(table):
print(column["name"], "-", column["type"])

IndentationError: expected an indented block after 'for' statement on line 5 (423091011.py, line 6)

In [84]:
import sys
import importlib

sys.path.insert(0, r"E:\Supermarket_Automation\python")

import main
importlib.reload(main)

main.test_database_connection()

Connected to PostgreSQL: supermarket_analytics

True

In [85]:
from pathlib import Path

base = Path(r"E:\Supermarket_Automation")

for folder in ["products", "sales", "inventory"]:
    files = list((base / "incoming" / folder).glob("*.csv"))
    print(f"{folder}: {len(files)} CSV file(s)")

products: 1 CSV file(s)
sales: 0 CSV file(s)
inventory: 0 CSV file(s)

In [86]:
import sys

sys.path.insert(0, r"E:\Supermarket_Automation\python")

import main
main.main()

Processing: products_test.csv
Validation: Validation successful: 2 rows checked.
Rows before cleaning: 2
Duplicate rows removed: 0
Rows after cleaning: 2

Cleaned data preview:
   product_id product_name category  cost_price  selling_price  reorder_level
0        9001    Test Rice   Grains          40             55             10
1        9002     Test Oil  Grocery          90            120              5

Rows ready for import: 2
Preview complete. Nothing was imported into PostgreSQL.